### model
model_name_or_path: /home/mila/i/islamria/scratch/umong/Qwen2.5-32B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16

### dataset
dataset: nlgraph
template: qwen
cutoff_len: 4096
overwrite_cache: true

### output
output_dir: /home/mila/i/islamria/scratch/umong/qwen2.5-32b-nlgraph/lora/sft
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
resume_from_checkpoint: false
save_total_limit: 1
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
